"use client"

import "./globals.css";
import { Inter } from "next/font/google";

import Navbar from "./components/navbar";
import { useState } from "react";
import { ThemeContext } from "./Contexts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [theme, setTheme] = useState("dark");
  return (
    <html lang="en" className={theme}>
      <ThemeContext.Provider value={{theme, setTheme}}>
        <body className={inter.className + " bg-white dark:bg-black"}>
          <Navbar />
          {children}
        </body>
      </ThemeContext.Provider>
    </html>
  );
}
